# Generated by Django 3.2.4 on 2021-06-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
