# Generated by Django 3.2.4 on 2021-06-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_photo_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
