# Generated by Django 3.2.4 on 2021-06-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210621_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='board',
            name='modify_date',
        ),
    ]
